(defun language_lesson (l)
    (cond ((>= 0 l) (lesson_one))
	  ((= 1 l) (lesson_two))
	  ((= 2 l) (lesson_three))
	  ((= 3 l) (lesson_four))
	  ((= 4 l) (lesson_five))
	  ((= 5 l) (lesson_six))
	  ((= 6 l) (lesson_seven))
	  ((= 7 l) (lesson_eight))
	  ((= 8 l) (lesson_nine))
	  ((= 9 l) (lesson_ten))
	  (t (lesson_ten))
    )
)

(defun lesson_one ()
    (cls)
    (princ "You are authorized to use the following commands: ")
    (terpri) (terpri)
    (princ "Teleport: je vais")
    (fresh-line)
    (princ "Fireball: je fais un feu")
    (fresh-line)
    (princ "Eat: je mange")
    (fresh-line)
    (princ "Drink: je bois")
    (fresh-line)
    (princ "Heal: je suis en bonne sante")
    (fresh-line)
    (princ "Use: je utilise")
    (lesson_input 0)
)

(defun lesson_two ()
    (cls)
    (princ "Level 1 vocabulary: ")
    (terpri) (terpri)
    (princ "a fireball: une boule de feu")
    (lesson_input 1)
)

(defun lesson_three ()
    (cls)
    (princ "Level 2 vocabulary: ")
    (terpri) (terpri)
    (princ "the fire: le feu")
    (fresh-line)
    (princ "the fireball: la boule de feu")
    (lesson_input 2)
)

(defun lesson_four ()
    (cls)
    (princ "Level 3 vocabulary: ")
    (terpri) (terpri)
    (princ "this fire: ce feu")
    (fresh-line)
    (princ "this fireball: cette boule de feu")
    (lesson_input 3)
)

(defun lesson_five ()
    (cls)
    (princ "Level 4 vocabulary: ")
    (terpri) (terpri)
    (princ "we (m) / we (f) make: nous faisons")
    (fresh-line)
    (princ "we (m) / we (f) go: nous allons")
    (fresh-line)
    (princ "we (m) / we (f) eat: nous mangeons")
    (fresh-line)
    (princ "we (m) / we (f) drink: nous buvons")
    (fresh-line)
    (princ "we (m) / we (f) are well: nous sommes en bonne sante")
    (fresh-line)
    (princ "we (m) / we (f) use: nous utilisons")
    (lesson_input 4)
)

(defun lesson_six ()
    (cls)
    (princ "Level 5 vocabulary: ")
    (terpri) (terpri)
    (princ "that fire: ce feu")
    (fresh-line)
    (princ "that fireball: cette boule de feu")
    (lesson_input 5)
)

(defun lesson_seven ()
    (cls)
    (princ "Level 6 vocabulary: ")
    (terpri) (terpri)
    (princ "he / she makes: il / elle fait")
    (fresh-line)
    (princ "he / she goes: il / elle va")
    (fresh-line)
    (princ "he / she eats: il / elle mange")
    (fresh-line)
    (princ "he / she drinks: il / elle boit")
    (fresh-line)
    (princ "he / she is well: il / elle est en bonne sante")
    (fresh-line)
    (princ "he / she uses: il / elle utilise")
    (lesson_input 6)
)

(defun lesson_eight ()
    (cls)
    (princ "Level 7 vocabulary: ")
    (terpri) (terpri)
    (princ "they (m) / they (f) make: ils / elles font")
    (fresh-line)
    (princ "they (m) / they (f) go: ils / elles vont")
    (fresh-line)
    (princ "they (m) / they (f) eat: ils / elles mangent")
    (fresh-line)
    (princ "they (m) / they (f) drink: ils / elles boivent")
    (fresh-line)
    (princ "they (m) / they (f) are: ils / elles sont")
    (lesson_input 7)
)

(defun lesson_nine ()
    (cls)
    (princ "Level 8 vocabulary: ")
    (terpri) (terpri)
    (princ "you (informal) / you (formal) make: tu fais / vous faites")
    (fresh-line)
    (princ "you (informal) / you (formal) go: tu vas / vous allez")
    (fresh-line)
    (princ "you (informal) / you (formal) eat: tu manges / vous mangez")
    (fresh-line)
    (princ "you (informal) / you (formal) drink: tu bois / vous buvez")
    (fresh-line)
    (princ "you (informal) / you (formal) are: tu es / vous etes")
    (fresh-line)
    (princ "you (informal) / you (formal) use: tu utilises / vous utilisez")
    (lesson_input 8)
)

(defun lesson_ten ()
    (cls)
    (princ "Level 9 vocabulary: ")
    (terpri) (terpri)
    (princ "the fires: les feux")
    (fresh-line)
    (princ "the fireballs: las boules de feu")
    (fresh-line)
    (princ "some fires: des feux")
    (fresh-line)
    (princ "some fireballs: des boules de feu")
    (fresh-line)
    (princ "these \ those fires: ces feux")
    (fresh-line)
    (princ "these \ those fireballs: ces boules de feu")
    (lesson_input 9)
)

(defun lesson_input (n)
  (terpri) (terpri)
  (when (> n 0) (princ "[p]revious, "))
  (when (> (player-level *player*) n) (princ "[n]ext, "))
  (princ "Spacebar to continue.")
    (let ((ri (read_input)))
	(cond 
	    ((equal ri '(#\p)) (language_lesson (1- n))) 
	    ((and (equal ri '(#\n)) (> (player-level *player*) n)) (language_lesson (1+ n))) 
	    ((or (equal ri '(#\Space)) (equal ri '(#\Escape)))(draw_world) (fresh-line))
	    (t (cls) (language_lesson n))
	)
    )
)
