(defparameter *L1-pronouns* ())
(defparameter *L1-pronoun* nil)
(defparameter *L2-pronoun* nil)
(defparameter *noun-gender* nil)
(defparameter *pronoun-gender* nil)
(defparameter *formality* nil)
(defparameter *article-list* nil)
