(defun update_satiation ()
	(decf (player-satiation *player*) .5)
	(when (> (player-satiation *player*) 2500) (message "You are full."))
	(when (> (player-satiation *player*) 2500) (setf (player-satiation *player*) 2500))
	(when (> (player-satiation *player*) 200) (clear_hunger_status *player*))
	(when (= (player-satiation *player*) 200) (hunger_status 'hungry *player*))
	(when (= (player-satiation *player*) 100) (hunger_status 'hungry! *player*))
	(when (= (player-satiation *player*) 50) (hunger_status 'starving *player*))
	(when (< (player-satiation *player*) 1) (message "You starve to death.") 
						(setf (player-hitpoints *player*) 0)
						(setf *cause-of-death* "starved to death"))
)

(defun hunger_status (s creature)
	(clear_hunger_status creature)
	(push s (creature-status_effects creature))
)

(defun clear_hunger_status (creature)
	(setf (creature-status_effects creature) (remove 'hungry (creature-status_effects creature)))
	(setf (creature-status_effects creature) (remove 'hungry! (creature-status_effects creature)))
	(setf (creature-status_effects creature) (remove 'starving (creature-status_effects creature)))
)
