(defun language_lesson (l)
    (cond ((>= 0 l) (lesson_one))
	  ((= 1 l) (lesson_two))
	  ((= 2 l) (lesson_three))
	  ((= 3 l) (lesson_four))
	  ((= 4 l) (lesson_five))
	  ((= 5 l) (lesson_six))
	  ((= 6 l) (lesson_seven))
	  ((= 7 l) (lesson_eight))
	  ((= 8 l) (lesson_nine))
	  ((= 9 l) (lesson_ten))
	  (t (lesson_ten))
    )
)

(defun lesson_one ()
    (cls)
    (princ "You are authorized to use the following commands: ")
    (terpri) (terpri)
    (princ "Teleport: yo voy")
    (fresh-line)
    (princ "Fireball: yo hago un fuego")
    (fresh-line)
    (princ "Eat: yo como")
    (fresh-line)
    (princ "Drink: yo bebo")
    (fresh-line)
    (princ "Heal: yo estoy bien")
    (fresh-line)
    (princ "Use: yo uso")
    (lesson_input 0)
)

(defun lesson_two ()
    (cls)
    (princ "Level 1 vocabulary: ")
    (terpri) (terpri)
    (princ "a fireball: una bola de fuego")
    (lesson_input 1)
)

(defun lesson_three ()
    (cls)
    (princ "Level 2 vocabulary: ")
    (terpri) (terpri)
    (princ "the fire: el fuego")
    (fresh-line)
    (princ "the fireball: la bola de fuego")
    (lesson_input 2)
)

(defun lesson_four ()
    (cls)
    (princ "Level 3 vocabulary: ")
    (terpri) (terpri)
    (princ "this fire: este fuego")
    (fresh-line)
    (princ "this fireball: esta bola de fuego")
    (lesson_input 3)
)

(defun lesson_five ()
    (cls)
    (princ "Level 4 vocabulary: ")
    (terpri) (terpri)
    (princ "we (m) / we (f) make: nosotros / nosotras hacemos")
    (fresh-line)
    (princ "we (m) / we (f) go: nosotros / nosotras vamos")
    (fresh-line)
    (princ "we (m) / we (f) eat: nosotros / nosotras comemos")
    (fresh-line)
    (princ "we (m) / we (f) drink: nosotros / nosotras bebemos")
    (fresh-line)
    (princ "we (m) / we (f) are well: nosotros / nosotras estamos bien")
    (fresh-line)
    (princ "we (m) / we (f) use: nosotros / nosotras usamos")
    (lesson_input 4)
)

(defun lesson_six ()
    (cls)
    (princ "Level 5 vocabulary: ")
    (terpri) (terpri)
    (princ "that fire: ese fuego")
    (fresh-line)
    (princ "that fireball: esa bola de fuego")
    (lesson_input 5)
)

(defun lesson_seven ()
    (cls)
    (princ "Level 6 vocabulary: ")
    (terpri) (terpri)
    (princ "he / she makes: el / ella hace")
    (fresh-line)
    (princ "he / she goes: el / ella va")
    (fresh-line)
    (princ "he / she eats: el / ella come")
    (fresh-line)
    (princ "he / she drinks: el / ella bebe")
    (fresh-line)
    (princ "he / she is well: el / ella esta bien")
    (fresh-line)
    (princ "he / she uses: el / ella usa")
    (lesson_input 6)
)

(defun lesson_eight ()
    (cls)
    (princ "Level 7 vocabulary: ")
    (terpri) (terpri)
    (princ "they (m) / they (f) make: ellos / ellas hacen")
    (fresh-line)
    (princ "they (m) / they (f) go: ellos / ellas van")
    (fresh-line)
    (princ "they (m) / they (f) eat: ellos / ellas comen")
    (fresh-line)
    (princ "they (m) / they (f) drink: ellos / ellas beben")
    (fresh-line)
    (princ "they (m) / they (f) are well: ellos / ellas estan bien")
    (lesson_input 7)
)

(defun lesson_nine ()
    (cls)
    (princ "Level 8 vocabulary: ")
    (terpri) (terpri)
    (princ "you (informal) / you (formal) / you (plural) make: tu haces / usted hace / ustedes hacen")
    (fresh-line)
    (princ "you (informal) / you (formal) / you (plural) go: tu vas / usted va / ustedes van")
    (fresh-line)
    (princ "you (informal) / you (formal) / you (plural) eat: tu comes / usted come / ustedes comen")
    (fresh-line)
    (princ "you (informal) / you (formal) / you (plural) drink: tu bebes / usted bebe / ustedes beben")
    (fresh-line)
    (princ "you (informal) / you (formal) / you (plural) are well: tu estas bien / usted esta bien / ustedes estan bien")
    (fresh-line)
    (princ "you (informal) / you (formal) / you (plural) use: tu usas / usted usa / ustedes usan")
    (lesson_input 8)
)

(defun lesson_ten ()
    (cls)
    (princ "Level 9 vocabulary: ")
    (terpri) (terpri)
    (princ "the fires: los fuegos")
    (fresh-line)
    (princ "the fireballs: las bolas de fuego")
    (fresh-line)
    (princ "some fires: unos fuegos")
    (fresh-line)
    (princ "some fireballs: unas bolas de fuego")
    (fresh-line)
    (princ "these fires: estos fuegos")
    (fresh-line)
    (princ "those fires: esos fuegos")
    (fresh-line)
    (princ "these fireballs: estas bolas de fuego")
    (fresh-line)
    (princ "those fireballs: esas bolas de fuego")
    (lesson_input 9)
)

(defun lesson_input (n)
  (terpri) (terpri)
  (when (> n 0) (princ "[p]revious, "))
  (when (> (player-level *player*) n) (princ "[n]ext, "))
  (princ "Spacebar to continue.")
    (let ((ri (read_input)))
	(cond 
	    ((equal ri '(#\p)) (language_lesson (1- n))) 
	    ((and (equal ri '(#\n)) (> (player-level *player*) n)) (language_lesson (1+ n))) 
	    ((or (equal ri '(#\Space)) (equal ri '(#\Escape)))(draw_world) (fresh-line))
	    (t (cls) (language_lesson n))
	)
    )
)
