(defun player_choice ()
  (let ((ri (read_input)))
    (cond ((equal ri '(#\n)) (setf *session* nil) (setf *level* 21) (load "code/game_loader.fas"))
          ((equal ri '(#\t)) (setf *session* nil) (setf *level* 0) (load "code/tutorial.fas"))
	  ((equal ri '(#\q)) (quit))
	  (t (player_choice))
    )
  )
)

(princ "[n]ew game")
(fresh-line) 
(princ "[t]utorial")
(fresh-line) 
(princ "[q]uit")
(fresh-line) 
(player_choice)
