(defparameter *start-time* nil)
(defparameter *end-time* nil)

(defun game_loop () (if (equal *session* "Quit") (progn 
    (cls)
    (message "Goodbye.")
    (disp_messages)
    (draw_world)
    (setf *end-time* (get-universal-time))
    (sleep 1)
    (death_screen)
    )
  (progn 
    (setf (player-x-location *player*) *player-x*) 
    (setf (player-y-location *player*) *player-y*)
    (incturn)
    (enforce_minmax)
    (regenerate)
    (update_status_effects)
    (update_satiation)
    (update_hydration)
    (update_player_level)
    (new_lesson)
    (walk_over)
    (message nil)
    (draw_world)
    (fresh-line)
    (setf *fuego* nil)
    (read_keyboard)
    (update_creatures)
    (when (creature-dead *player*) 
	(message "You die.")
	(setf *session* "Quit"))
    (game_loop))))

(load "code\\game_init.fas")
(load "code\\draw_title.fas")
(load "code\\game_parameters.fas")
(load "code\\win_display_functions.fas")
(load "code\\io_functions.fas")
(cls)
(intro_screen)
(load "code\\start_menu.fas")
