(load "code\\rand_functions.fas")
(load "code\\teleport.fas")
(load "code\\draw_title.fas")
(load "code\\message_passer.fas")
(load "code\\level_maker.fas")
(load "code\\init_monsters.fas")
(load "code\\monsters.fas")
(load "code\\make_hero.fas")
(load "code\\update_creatures.fas")
(load "code\\status_bar.fas")
(load "code\\game_init.fas")    
(load "code\\player_movement.fas")
(load "code\\io_functions.fas")
(load "code\\show_inventory.fas")
(load "code\\items.fas")
(load "code\\set_language_parameters.fas")
(load "code\\line_of_sight.fas")
(load "code\\choose_language.fas")
(load "code\\dice.fas")
(load "code\\player_level.fas")
(load "code\\combat_functions.fas")
(load "code\\satiation.fas")
(load "code\\hydration.fas")
(load "code\\english_conjugations.fas")
(load "code\\command_generator.fas")
(load "code\\new_lesson.fas")
(load "code\\turn.fas")
(load "code\\regeneration.fas")
(load "code\\status_conditions.fas")
(load "code\\death_screen.fas")
(load "code\\target.fas")
(load "code\\ranged.fas")
(load "code\\trash_talk.fas")
(load "code\\L2-error.fas")

(create_player)
(race_modify)
(choose_language)
(cond ((equal *L2* "Spanish") (load "code\\spanish_conjugations.fas")
                              (load "code\\spanish_trans.fas")
                              (load "code\\spanish_lessons.fas")
      )
      ((equal *L2* "French") (load "code\\french_conjugations.fas")
                             (load "code\\french_trans.fas")
                             (load "code\\french_lessons.fas")
      )
)
(set-pronoun)
(new_level)
(language_lesson 0)
(setf *start-time* (get-universal-time))
(game_loop)
(load "code\\start_menu.fas")
