(defun player_choice ()
  (let ((ri (read_input)))
    (cond ((equal ri '(#\n)) (setf *session* nil) (load "code\\game_loader.fas"))
	  ((equal ri '(#\q)) (quit))
	  (t (player_choice))
    )
  )
)

(princ "[n]ew game")
(fresh-line) 
(princ "[q]uit")
(fresh-line) 
(player_choice)
