(defun choose_language ()
    (cls)
    (princ "Which language would you like to learn?")
    (fresh-line)
    (princ "[1] Esperanto")
    (fresh-line)
    (princ "[2] French")
    (fresh-line)
    (princ "[3] Spanish")
    (fresh-line)
    (let ((ri (read_input)))
        (cond ((equal ri '(#\1)) (setf *L2* "Esperanto"))
              ((equal ri '(#\2)) (setf *L2* "French"))
              ((equal ri '(#\3)) (setf *L2* "Spanish"))
	      (t (progn (cls) (choose_language)))
        )
    )
)
