(defparameter *level-height* 35)
(defparameter *level-width* 120)
(defparameter *player-x* 14)
(defparameter *player-y* 14)
(defparameter *player-vision* 35)
(defparameter *rat-maximum* 20)
(defparameter *rat-vision* 6)
(defparameter *wolf-maximum* 10)
(defparameter *wolf-vision* 10)
(defparameter *blank-tile* " ")
(defparameter *player-tile* "@")
(defparameter *floor-tile* ".")
(defparameter *wall-tile-1* "#")
(defparameter *wall-tile-2* "+")
(defparameter *blank-status* " ")
(defparameter *blank-half-line* "                           ")
(defparameter *message* *blank-status*)
(defparameter *session* "Active")
(defparameter *tile-string* ())
(defparameter *fuego* nil)
(defparameter *room-maximum* 25)
(defparameter *jump-length* 5)
(defparameter *pronoun* nil)
(defparameter *language* nil)
(defparameter *level* 21)
(defparameter *stair-x* nil)
(defparameter *stair-y* nil)
(defparameter *access-code* nil)
