(defun game_loop () (if (equal *session* "Quit") (progn 
    (cls)
    (message "Goodbye.")
    (disp_messages)
    (draw_world)
    )
  (progn 
    (incturn)
    (enforce_minmax)
    (regenerate)
    (update_status_effects)
    (update_satiation)
    (update_hydration)
    (update_player_level)
    (new_lesson)
    (message nil)
    (draw_world)
    (fresh-line)
    (setf *fuego* nil)
    (read_keyboard)
    (update_creatures)
    (when (creature-dead *player*) 
	(message "You die.")
	(setf *session* "Quit"))
    (game_loop))))

(load "game_parameters.lisp")
(load "rand_functions.fas")
(load "teleport.lisp")
(load "change_color.lisp")
(load "drawwolf.lisp")
(load "draw_title.lisp")
(load "message_passer.lisp")
(load "map.fas")
(load "level_maker.lisp")
(load "init_monsters.lisp")
(load "monsters.fas")
(load "make_hero.lisp")
(load "update_creatures.fas")
(load "status_bar.fas")
(load "display_functions.fas")
(load "game_init.lisp")    
(load "player_movement.fas")
(load "io_functions.fas")
(load "show_inventory.lisp")
(load "items.lisp")
(load "weapons.lisp")
(load "armor.lisp")
(load "set_language_parameters.lisp")
(load "line_of_sight.fas")
(load "choose_language.lisp")
(load "dice.lisp")
(load "player_level.lisp")
(load "combat_functions.lisp")
(load "satiation.lisp")
(load "hydration.lisp")
(load "english_conjugations.lisp")
(load "command_generator.lisp")
(load "new_lesson.lisp")
(load "pause.lisp")
(load "turn.lisp")
(load "regeneration.lisp")
(load "status_conditions.lisp")
(intro_screen)
(create_player)
(race_modify)
(choose_language)
(cond ((equal *L2* "Spanish") (load "spanish_conjugations.lisp")
                              (load "spanish_trans.lisp")
                              (load "spanish_lessons.lisp")
      )
      ((equal *L2* "French") (load "french_conjugations.lisp"))
      ((equal *L2* "Esperanto") (load "esperanto_conjugations.lisp"))
)
(set-pronoun)
(new_level)
(language_lesson)
(game_loop)
(quit)
