(defun random-article ()
   (when (equal *language* "Spanish")
	(let ((r (random 8)))
	    (cond
		((= r 0) (setf *article* "el"))
		((= r 1) (setf *article* "la"))
		((= r 2) (setf *article* "un"))
		((= r 3) (setf *article* "una"))
		((= r 4) (setf *article* "los"))
		((= r 5) (setf *article* "las"))
		((= r 6) (setf *article* "unos"))
		((= r 7) (setf *article* "unas"))
	    )
	)
   )
    (when (equal *language* "French")
	(let ((r (random 8)))
	    (cond
		((= r 0) (setf *article* "le"))
		((= r 1) (setf *article* "la"))
		((= r 2) (setf *article* "un"))
		((= r 3) (setf *article* "une"))
		((= r 4) (setf *article* "les"))
		((= r 5) (setf *article* "des"))
	    )
	)
   )
   (when (equal *language* "Esperanto") (setf *article* "la"))
)

(defun random-pronoun (n)
   (when (equal *language* "Spanish")
     (let ((r (random n)))
	(cond  
	   ((= r 0) (setf *pronoun* "infinitive")) 
	   ((= r 1) (setf *pronoun* "yo")) 
	   ((= r 2) (setf *pronoun* "nosotros"))
	   ((= r 3) (setf *pronoun* "nosotras"))
	   ((= r 4) (setf *pronoun* "el"))
	   ((= r 5) (setf *pronoun* "ella"))
	   ((= r 6) (setf *pronoun* "usted"))
	   ((= r 7) (setf *pronoun* "ustedes"))
	   ((= r 8) (setf *pronoun* "ellos"))
	   ((= r 9) (setf *pronoun* "ellas"))
	   ((= r 10) (setf *pronoun* "tu"))
        )
      )
   )
   (when (equal *language* "French")
     (let ((r (random 8)))
	(cond  
	   ((= r 0) (setf *pronoun* "infinitive")) 
	   ((= r 1) (setf *pronoun* "je")) 
	   ((= r 2) (setf *pronoun* "nous"))
	   ((= r 3) (setf *pronoun* "il"))
	   ((= r 4) (setf *pronoun* "elle"))
	   ((= r 5) (setf *pronoun* "vous"))
	   ((= r 6) (setf *pronoun* "ils"))
	   ((= r 7) (setf *pronoun* "elles"))
	   ((= r 8) (setf *pronoun* "tu"))
        )
      )
  )
  (when (equal *language* "Esperanto")
     (let ((r (random 7)))
	(cond  
	   ((= r 0) (setf *pronoun* "infinitive")) 
	   ((= r 1) (setf *pronoun* "I")) 
	   ((= r 2) (setf *pronoun* "we"))
	   ((= r 3) (setf *pronoun* "he"))
	   ((= r 4) (setf *pronoun* "she"))
	   ((= r 5) (setf *pronoun* "it"))
	   ((= r 6) (setf *pronoun* "they"))
	   ((= r 7) (setf *pronoun* "you"))
        )
      )
  )
)
