;; initialization procedure
(defun intro_screen () (progn 
    (change_text_color 'red)
    (draw_skull)
    (fresh-line)
    (princ *blank-half-line*)
    (fresh-line)
    (change_text_color 'red)
    (princ "Press any key to continue.") 
    (change_text_color 'cyan)
    (read_input) 
    (cls)))

(defun draw_skull () (progn
(princ "                           .ed\"\"\"\" \"\"\"$$$$be.")
(fresh-line)
(princ "                         -\"           ^\"\"**$$$e.")
(fresh-line)
(princ "                       .\"                   '$$$c")
(fresh-line)
(princ "                      /                      \"4$$b")
(fresh-line)
(princ "                     d  3                      $$$$")
(fresh-line)
(princ "                     $  *                   .$$$$$$")
(fresh-line)
(princ "                    .$  ᶜ           $$$$$e$$$$$$$$.")
(fresh-line)
(princ "                    d$L  4.         4$$$$$$$$$$$$$$b")
(fresh-line)
(princ "                    $$$$b ^ceeeee.  4$$ECL.F*$$$$$$$")
(fresh-line)
(princ "        e$\"\"=.      $$$$P d$$$$F $ $$$$$$$$$- $$$$$$")
(fresh-line)
(princ "       z$$b. ᶜ     3$$$F \"$$$$b   $\"$$$$$$$  $$$$*\"      .=\"\"$c")
(fresh-line)
(princ "      4$$$$L        $$P\"  \"$$b   .$ $$$$$...e$$        .=  e$$$.")
(fresh-line)
(princ "      ^*$$$$$c  %..   *c    ..    $$ 3$$$$$$$$$$eF     zP  d$$$$$")
(fresh-line)
(princ "        \"**$$$ec   \"   %ce\"\"    $$$  $$$$$$$$$$*    .r\" =$$$$P\"\"")
(fresh-line)
(princ "              \"*$b.  \"c  *$e.    *** d$$$$$\"L$$    .d\"  e$$***\"")
(fresh-line)
(princ "                ^*$$c ^$c $$$      4J$$$$$% $$$ .e*\".eeP\"")
(fresh-line)
(princ "                   \"$$$$$$\"'$=e....$*$$**$cz$$\" \"..d$*\"")
(fresh-line)
(princ "                     \"*$$$  *=%4.$ L L$ P3$$$F $$$P\"")
(fresh-line)
(princ "                        \"$   \"%*ebJLzb$e$$$$$b $P\"")
(fresh-line)
(princ "                          %..      4$$$$$$$$$$ \"")
(fresh-line)
(princ "                           $$$e   z$$$$$$$$$$%")
(fresh-line)
(princ "                            \"*$c  \"$$$$$$$P\"")
(fresh-line)
(princ "                             .\"\"\"*$$$$$$$$bc")
(fresh-line)
(princ "                          .-\"    .$***$$$\"\"\"*e.")
(fresh-line)
(princ "                       .-\"    .e$\"     \"*$c  ^*b.")
(fresh-line)
(princ "                .=*\"\"\"\"    .e$*\"          \"*bc  \"*$e..")
(fresh-line)
(princ "              .$\"        .z*\"               ^*$e.   \"*****e.")
(fresh-line)
(princ "              $$ee$c   .d\"                     \"*$.        3.")
(fresh-line)
(princ "              ^*$E\")$..$\"                         *   .ee==d%")
(fresh-line)
(princ "                 $.d$$$*                           *  J$$$e*")
(fresh-line)
(princ "                  \"\"\"\"\"                              \"$$$\"")
(fresh-line)
(princ " @@@       @@@@@@  @@@  @@@  @@@@@@@  @@@@@@@   @@@@@@  @@@  @@@ @@@@@@@ ")
(fresh-line)
(princ " @@!      @@!  @@@ @@!@!@@@ !@@       @@!  @@@ @@!  @@@ @@!@!@@@ @@!  @@@")
(fresh-line)
(princ " @!!      @!@!@!@! @!@@!!@! !@! @!@!@ @!@!@!@  @!@!@!@! @!@@!!@! @!@  !@!")
(fresh-line)
(princ " !!:      !!:  !!! !!:  !!! :!!   !!: !!:  !!! !!:  !!! !!:  !!! !!:  !!!")
(fresh-line)
(princ " : ::.: :  :   : : ::    :   :: :: :  :: : ::   :   : : ::    :  :: :  : ")))
                                                                         

