(defun draw_squatch () (progn
(princ "                                        .OZOOO$+.                          ")
(fresh-line)
(princ "                                       .$O8O88DZ.                          ")    
(fresh-line)
(princ "                                      .$8ZMDDZMO$                          ")   
(fresh-line)
(princ "                                     ++OO7I?.=?+$?                         ")  
(fresh-line)
(princ "                                 . +,+7$7D?+$IIDZ?:,.                      ")
(fresh-line)
(princ "                                ,:~?7?IIZ877$=ID87?I?                      ")
(fresh-line)
(princ "                               ?++?+?I$$I$88Z8DZ?=77ZI+,.                  ") 
(fresh-line)
(princ "                              ~??+?=?7II$ON8DNOI++~??= ?+                  ") 
(fresh-line)
(princ "                              :=?=?:=+~=7?II$Z$I$+=~=~~~=.                 ")
(fresh-line)
(princ "                             .$I=+7+=~~~+=+7???+=?=I=~I?$:                 ")
(fresh-line)
(princ "                              =7$Z7$~I+=~?=??=+7I$I?OZ?O7:                 ")
(fresh-line)
(princ "                             .,7I$ZO7Z$7?=+7ZII7$?ZO$O$7?,.                ")
(fresh-line)
(princ "                             .+$I$ZZDD7+IOO$$$$?77$NMZ7=+                  ")
(fresh-line)
(princ "                             .II$$78O7Z$$7777I7II$88D$$?...                ")
(fresh-line)
(princ "                             ,+I,I7IIZ7$$+?II=+I?78787II?.                 ")
(fresh-line)
(princ "                             ??I~$7?$O?I+I=I~??$?$Z$7Z7?=.                 ")
(fresh-line)
(princ "                             ?I$I==7IZ?7++=7~=++IZZ~77OO$=                 ")
(fresh-line)
(princ "                             ,=7$+~I=$II~+~77=+=?$Z:7$O?7,.                ")
(fresh-line)
(princ "                              I7$7$+II???~==+===777.$7$I7I.                ")
(fresh-line)
(princ "                              .?~I$7=O7I7+~=+=I++7Z.???II?.                ")
(fresh-line)
(princ "                               .II$7I+I+?I?+I++=?I7.+$I?7I.                ")
(fresh-line)
(princ "                                 ~I7???I=++=?+~I++7.+77?$?.                ")
(fresh-line)
(princ "                                  7?$7II=?=??I7II??.++$$I~.                ")
(fresh-line)
(princ "                                  .7IZO$+I++??777+$,:?77Z=                 ")
(fresh-line)
(princ "                                  ,+$Z7$~7II+IZ$++7,=$$I~:                 ")
(fresh-line)
(princ "                                  ~=$=+7+7II7+II7+~=~O77=.                 ")
(fresh-line)
(princ "                                  ~=?ZD??7$$Z??7=::=I$7I7                  ")
(fresh-line)
(princ "                                  ,~77$I?II$7=I=?+~=$=O+:                  ")
(fresh-line)
(princ "                                  ,~==+I+7,?=7?I~~=7.O?~                   ")
(fresh-line)
(princ "                                 ..:+=I+7~ .~+:$+=+O8?                     ")
(fresh-line)
(princ "                                  .,=+I??....~+I?+??.                      ")
(fresh-line)
(princ "                                  .~?+7I+ . ..=??II.                       ")
(fresh-line)
(princ "                                  ,?7II+I.  .,?$Z+7.                       ")
(fresh-line)
(princ "                                  ~=777??. ..~=$O7=.                       ")
(fresh-line)
(princ "                                  ~+$?=Z8.  .Z7IZO=.                       ")
(fresh-line)
(princ "                                  :+$O?+Z....~?I77=.                       ")
(fresh-line)
(princ "                                 ..ZIZ7OI....=Z7?++,                       ")
(fresh-line)
(princ "                                  .7+7ZZ7. . I8O+I$.                       ")
(fresh-line)
(princ "                                 .+$+Z$~Z. ..IOI?+I:.                      ")
(fresh-line)
(princ "                                . ++$ZOI7  ..~N7$I+Z..                     ")
(fresh-line)
(princ "                                 ??=$?I.   .. M$7++~~,                     ")))
