(defun set-pronoun ()
   (when (equal *language* "Spanish")
     (let ((r (random 10)))
	(cond  
	   ((= r 0) (setf *pronoun* "yo")) 
	   ((= r 1) (setf *pronoun* "tu"))
	   ((= r 2) (setf *pronoun* "el"))
	   ((= r 3) (setf *pronoun* "ella"))
	   ((= r 4) (setf *pronoun* "usted"))
	   ((= r 5) (setf *pronoun* "ustedes"))
	   ((= r 6) (setf *pronoun* "ellos"))
	   ((= r 7) (setf *pronoun* "ellas"))
	   ((= r 8) (setf *pronoun* "nosotros"))
	   ((= r 9) (setf *pronoun* "nosotras"))
        )
      )
   )
   (when (equal *language* "French")
     (let ((r (random 8)))
	(cond  
	   ((= r 0) (setf *pronoun* "je")) 
	   ((= r 1) (setf *pronoun* "tu"))
	   ((= r 2) (setf *pronoun* "il"))
	   ((= r 3) (setf *pronoun* "elle"))
	   ((= r 4) (setf *pronoun* "vous"))
	   ((= r 5) (setf *pronoun* "ils"))
	   ((= r 6) (setf *pronoun* "elles"))
	   ((= r 7) (setf *pronoun* "nous"))
        )
      )
  )
  (when (equal *language* "Esperanto")
     (let ((r (random 7)))
	(cond  
	   ((= r 0) (setf *pronoun* "I")) 
	   ((= r 1) (setf *pronoun* "you"))
	   ((= r 2) (setf *pronoun* "he"))
	   ((= r 3) (setf *pronoun* "she"))
	   ((= r 4) (setf *pronoun* "it"))
	   ((= r 5) (setf *pronoun* "they"))
	   ((= r 6) (setf *pronoun* "we"))
        )
      )
  )
)
